---
- name: Update log4j packages on TSM VE 8.1.13 datamovers
  hosts: all
  vars:
    log4jdir: apache-log4j-2.17.0-bin/
    log4jfiles:
      - log4j-1.2-api-2.17.0.jar
      - log4j-api-2.17.0.jar
      - log4j-core-2.17.0.jar
      - log4j-jcl-2.17.0.jar
      - log4j-slf4j-impl-2.17.0.jar
  tasks:
    - name: Download and extract log4j package
      unarchive:
        src: https://dlcdn.apache.org/logging/log4j/2.17.0/apache-log4j-2.17.0-bin.tar.gz
        dest: "{{ playbook_dir }}"
        remote_src: yes
      run_once: true
      delegate_to: 127.0.0.1
      # when: 0 > 1

    - name: Check files
      stat:
        path: "{{ log4jdir }}{{ item }}"
      loop: "{{ log4jfiles }}"
      register: stat_result
      failed_when: not stat_result.stat.exists
      run_once: true
      delegate_to: 127.0.0.1

    - name: Stop services
      systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - dsmcad
        - webserver

    - name: Copy new files to tdpvmware
      copy:
        src: "{{ item }}"
        dest: "/opt/tivoli/tsm/tdpvmware/common/lib/"
        owner: tdpvmware
        group: tdpvmware
        mode: 0775
      loop:
        - "{{ log4jdir }}log4j-api-2.17.0.jar"
        - "{{ log4jdir }}log4j-core-2.17.0.jar"

    - name: Remove old files from tdpvmware
      file:
        path: "/opt/tivoli/tsm/tdpvmware/common/lib/{{ item }}"
        state: absent
      loop:
        - log4j-api-2.13.3.jar
        - log4j-core-2.13.3.jar

    - name: Copy new files to FR_API
      copy:
        src: "{{ item }}"
        dest: "/opt/tivoli/tsm/tdpvmware/common/webserver/usr/servers/veProfile/apps/FR_API.war/WEB-INF/lib/"
        owner: tdpvmware
        group: tdpvmware
        mode: 0775
      loop:
        - "{{ log4jdir }}log4j-1.2-api-2.17.0.jar"
        - "{{ log4jdir }}log4j-api-2.17.0.jar"
        - "{{ log4jdir }}log4j-core-2.17.0.jar"

    - name: Remove old files from FR_API
      file:
        path: "/opt/tivoli/tsm/tdpvmware/common/webserver/usr/servers/veProfile/apps/FR_API.war/WEB-INF/lib/{{ item }}"
        state: absent
      loop:
        - log4j-1.2-api-2.13.3.jar
        - log4j-api-2.13.3.jar
        - log4j-core-2.13.3.jar

    - name: Copy new files to SDK
      copy:
        src: "{{ item }}"
        dest: "/opt/tivoli/tsm/client/ba/bin/plugins/vcloudsuite/sdk/"
        owner: root
        group: bin
        mode: 0555
      loop:
        - "{{ log4jdir }}log4j-api-2.17.0.jar"
        - "{{ log4jdir }}log4j-core-2.17.0.jar"
        - "{{ log4jdir }}log4j-jcl-2.17.0.jar"
        - "{{ log4jdir }}log4j-slf4j-impl-2.17.0.jar"

    - name: Remove old files from SDK
      file:
        path: "/opt/tivoli/tsm/client/ba/bin/plugins/vcloudsuite/sdk/{{ item }}"
        state: absent
      loop:
        - log4j-api-2.13.3.jar
        - log4j-core-2.13.3.jar
        - log4j-jcl-2.13.3.jar
        - log4j-slf4j-impl-2.13.3.jar

    - name: Start services
      systemd:
        name: "{{ item }}"
        state: started
      loop:
        - dsmcad
        - webserver
